services:
  - type: web
    name: votehubph-backend
    env: php
    buildCommand: composer install --optimize-autoloader --no-dev
    startCommand: php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false

